// User simuled data
export const users = {
    testCashier: {
        id: 99996,
        name: 'Test Juan Pérez',
        role: 'Cajero',
        user_name: 'testjuanperez',
        email: 'test.juan.perez@example.com',
        password: '$2a$10$mpnWHTXDlbuC/DfFMoqsEe03Z9yvtxU8DQgkDbdUiHk9HS2OymNwK',
        phone: '5551234567',
        age: 30,
        dpi_number: '9999999999991',
        photo_path: 'https://example.com/photography/test_men.jpg',
        signature_path: 'https://example.com/signature/test.png',
        gender: 'Masculino',
        marital_status: 'Soltero',
        created_at: Math.floor(Date.now() / 1000),
    },
    testCustomerService: {
        id: 99997,
        name: 'Test Ana López',
        role: 'Atención al Cliente',
        user_name: 'testanalopez',
        email: 'test.ana.lopez@example.com',
        password: '$2a$10$mpnWHTXDlbuC/DfFMoqsEe03Z9yvtxU8DQgkDbdUiHk9HS2OymNwK',
        phone: '5559876543',
        age: 28,
        dpi_number: '9999999999992',
        photo_path: 'https://example.com/photography/test_woman.jpg',
        signature_path: 'https://example.com/signature/test.png',
        gender: 'Femenino',
        marital_status: 'Casado',
        created_at: Math.floor(Date.now() / 1000),
    },
    testSupervisor: {
        id: 99998,
        name: 'Test Luis Rodríguez',
        role: 'Supervisor',
        user_name: 'testluisrodriguez',
        email: 'test.luis.rodriguez@example.com',
        password: '$2a$10$mpnWHTXDlbuC/DfFMoqsEe03Z9yvtxU8DQgkDbdUiHkDbdUiHkDbdUiHkDbdUiHkDbdUiHkDbdUiHkDbdUiHkDbdUiHkDbdUiHkDbdUiHk',
        phone: '5556789012',
        age: 40,
        dpi_number: '9999999999993',
        photo_path: 'https://example.com/photography/test_men.jpg',
        signature_path: 'https://example.com/signature/test.png',
        gender: 'Masculino',
        marital_status: 'Casado',
        hashedSecondPassword: '$2a$10$mpnWHTXDlbuC/DfFMoqsEe03Z9yvtxU8DQgkDbdUiHkDbdUiHkDbdUiHkDbdUiHkDbdUiHk',
        created_at: Math.floor(Date.now() / 1000),
    },
    testAdmin: {
        id: 99999,
        name: 'Test María García',
        role: 'Administrador de Sistemas',
        user_name: 'testmariagarcia',
        email: 'test.maria.garcia@example.com',
        password: '$2a$10$mpnWHTXDlbuC/DfFMoqsEe03Z9yvtxU8DQgkDbdUiHkDbdUiHkDbdUiHkDbdUiHkDbdUiHkDbdUiHk',
        phone: '5553456789',
        age: 35,
        dpi_number: '9999999999994',
        photo_path: 'https://example.com/photography/test_woman.jpg',
        signature_path: 'https://example.com/signature/test.png',
        gender: 'Femenino',
        marital_status: 'Divorciado',
        hashedSecondPassword: '$2a$10$mpnWHTXDlbuC/DfFMoqsEe03Z9yvtxU8DQgkDbdUiHkDbdUiHkDbdUiHkDbdUiHkDbdUiHk',
        created_at: Math.floor(Date.now() / 1000),
    },
};

export const accounts = {
    testAccount1: {
        id: 99996,
        account_number: '9999999996',
        cui: '9999999999995',
        name: 'Carlos',
        last_name: 'Pérez',
        phone: '5551234567',
        email: 'test.carlos.perez@example.com',
        age: 30,
        gender: 'Masculino',
        photo_path: 'https://money-bin-group2.s3.us-east-1.amazonaws.com/photography/test_men.jpg',
        account_type: 'Ahorro',
        currency: 'Quetzales',
        balance: 10000.00,
        created_at: Math.floor(Date.now() / 1000),
        update_balance_at: Math.floor(Date.now() / 1000),
        security_question: '¿Cuál es el nombre de tu mascota?',
        security_answer: 'Rex',
    },
    testAccount2: {
        id: 99997,
        account_number: '9999999997',
        cui: '9999999999996',
        name: 'Ana',
        last_name: 'López',
        phone: '5559876543',
        email: 'test.ana.lopez@example.com',
        age: 28,
        gender: 'Femenino',
        photo_path: 'https://money-bin-group2.s3.us-east-1.amazonaws.com/photography/test_woman.jpg',
        account_type: 'Ahorro',
        currency: 'Dólares',
        balance: 3000.00,
        created_at: Math.floor(Date.now() / 1000),
        update_balance_at: Math.floor(Date.now() / 1000),
        security_question: '¿Cuál es tu ciudad natal?',
        security_answer: 'Guatemala',
    },
    testAccount3: {
        id: 99998,
        account_number: '9999999998',
        cui: '9999999999997',
        name: 'Luis',
        last_name: 'Gómez',
        phone: '5558765432',
        email: 'test.luis.gomez@example.com',
        age: 35,
        gender: 'Masculino',
        photo_path: 'https://money-bin-group2.s3.us-east-1.amazonaws.com/photography/test_men.jpg',
        account_type: 'Monetario',
        currency: 'Quetzales',
        balance: 1200.00,
        created_at: Math.floor(Date.now() / 1000),
        update_balance_at: Math.floor(Date.now() / 1000),
        security_question: '¿Cuál es tu color favorito?',
        security_answer: 'Azul',
    },
    testAccount4: {
        id: 99999,
        account_number: '9999999999',
        cui: '9999999999998',
        name: 'María',
        last_name: 'Rodríguez',
        phone: '5556543210',
        email: 'test.maria.rodriguez@example.com',
        age: 29,
        gender: 'Femenino',
        photo_path: 'https://money-bin-group2.s3.us-east-1.amazonaws.com/photography/test_woman.jpg',
        account_type: 'Monetario',
        currency: 'Dólares',
        balance: 1150.00,
        created_at: Math.floor(Date.now() / 1000),
        update_balance_at: Math.floor(Date.now() / 1000),
        security_question: '¿Cómo se llama tu mejor amigo?',
        security_answer: 'Sofía',
    },
};

// Endpoints
export const endpoints = {
    accounts: '/api/accounts',
    withdrawal: '/api/withdrawal',
    deposit: '/api/deposit',
    create_card: '/api/create-card',
    service_payment_cashier: '/api/payment-service/cashier',
};
