name: CI/CD Pipeline for backend-money-bin

on:
  push:
    branches:
      - main
      - feature202030987_ci-cd-backend

permissions:
  contents: write
  actions: read

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    environment: EC2

    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run Integration Tests
        run: |
          cd backend
          npm test -- --selectProjects integration --detectOpenHandles

      - name: Set up Docker
        run: |
          echo "Ensuring Docker is installed"
          docker --version

      - name: Build Docker image
        run: |
          docker build -t backend-money-bin:latest -f backend/Dockerfile backend

      - name: Save Docker image to file
        run: |
          docker save backend-money-bin:latest | gzip > backend-money-bin-latest.tar.gz

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Prepare known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Add known hosts
        run: |
          ssh-keyscan -H ${{ secrets.BACKEND_IP }} 2>/dev/null >> ~/.ssh/known_hosts || true

      - name: Transfer Docker image to EC2
        run: |
          scp backend-money-bin-latest.tar.gz ubuntu@${{ secrets.BACKEND_IP }}:/home/ubuntu/

      - name: Deploy Backend to EC2
        run: |
          ssh ubuntu@${{ secrets.BACKEND_IP }} << 'EOF'
          cd /home/ubuntu
          docker load < backend-money-bin-latest.tar.gz
          docker-compose down
          docker-compose up -d
          EOF
