name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature202030987_ci-cd

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "Running tests..."
          echo "Tests passed!"
