name: CI Pipeline for backend-money-bin

on:
  push:
    branches:
      - main
      - feature202030987_ci-cd-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          echo "Ensuring Docker is installed"
          docker --version

      - name: Build and Test Docker image
        run: |
          docker build -t backend-money-bin:latest -f backend/Dockerfile backend

      - name: Save Docker image to file
        run: |
          docker save backend-money-bin:latest | gzip > backend-money-bin-latest.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-money-bin-latest
          path: backend-money-bin-latest.tar.gz
